/**
 * @File Name          : TestLanguageCourseTrigger.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 9/3/2019, 7:40:16 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    9/3/2019   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
@isTest
public without sharing class TestLanguageCourseTrigger {
    @isTest static void testCheckDates() {
        
    } 
}
